import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { ArrowLeft, Camera, CheckCircle2, MapPin, PackageCheck, Send, ShieldCheck } from 'lucide-react';
import { AdminPageHeader } from '@/components/admin/AdminPageHeader';
import { ItemStateBadge } from '@/components/admin/inbound/ItemStateBadge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { workflowService } from '@/services/inbound/workflowService';
import { useAdmin } from '@/hooks/useAdmin';
import { fileToCompressedDataUrl } from '@/lib/imageCapture';

const money=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function InboundItemDetail(){
  const {id}=useParams(); const nav=useNavigate(); const qc=useQueryClient(); const {roles}=useAdmin();
  const {data,isLoading}=useQuery({queryKey:['inbound','item',id],queryFn:()=>workflowService.detail(String(id)),enabled:!!id});
  const {data:locations=[]}=useQuery({queryKey:['inbound','locations'],queryFn:workflowService.locations});
  const item=data?.item; const [notes,setNotes]=useState(''); const [location,setLocation]=useState(''); const [price,setPrice]=useState(''); const [sku,setSku]=useState(''); const [title,setTitle]=useState('');
  const [photoCaption,setPhotoCaption]=useState('');
  const allowed=(list:string[])=>roles.some(role=>list.includes(role));
  const refresh=()=>{qc.invalidateQueries({queryKey:['inbound','item',id]});qc.invalidateQueries({queryKey:['inbound','items']});};
  const action=useMutation({mutationFn:async(input:{kind:string;decision?:string})=>{if(!item)throw new Error('Item não encontrado');if(input.kind==='qc')return workflowService.qc(item.id,String(input.decision),notes);if(input.kind==='price')return workflowService.price(item.id,Number(price||item.approved_price||item.suggested_price),notes);if(input.kind==='address')return workflowService.address(item.id,location||item.location_id||'');if(input.kind==='stock')return workflowService.stock(item.id);return workflowService.release(item.id,title||item.title||'',sku||item.sku||'',Number(price||item.approved_price||item.suggested_price),notes);},onSuccess:()=>{refresh();toast.success('Etapa concluída');},onError:(e:Error)=>toast.error('Não foi possível concluir',{description:e.message})});
  const upload=useMutation({mutationFn:async(file:File)=>workflowService.uploadPhoto(item.id,await fileToCompressedDataUrl(file),'evidence',photoCaption),onSuccess:()=>{refresh();setPhotoCaption('');toast.success('Foto de evidência salva');},onError:(e:Error)=>toast.error('Não foi possível salvar a foto',{description:e.message})});
  const photos=(data?.photos??[]) as Array<Record<string,any>>; const market=(data?.market??[]) as Array<Record<string,any>>; const events=(data?.events??[]) as Array<Record<string,any>>; const movements=(data?.movements??[]) as Array<Record<string,any>>;
  const margin=useMemo(()=>{const p=Number(price||item?.approved_price||item?.suggested_price);const c=Number(item?.cost);return p>0&&c>=0?((p-c)/p)*100:null;},[price,item]);
  if(isLoading)return <p className="text-sm text-muted-foreground">Carregando SKU...</p>; if(!item)return <p>SKU não encontrado.</p>;
  return <div className="space-y-6"><AdminPageHeader title={item.title||'SKU em processamento'} subtitle={[item.sku,item.barcode].filter(Boolean).join(' · ')||'Sem código'} actions={<Button variant="outline" onClick={()=>nav(-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Voltar</Button>}/>
    <div className="flex flex-wrap gap-2"><ItemStateBadge state={item.state}/><span className="text-sm text-muted-foreground">{item.quantity} un. · condição {item.condition_code}</span></div>
    <Tabs defaultValue="summary"><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="summary">SKU</TabsTrigger><TabsTrigger value="photos">Fotos</TabsTrigger><TabsTrigger value="market">Mercado</TabsTrigger><TabsTrigger value="history">Histórico</TabsTrigger></TabsList>
      <TabsContent value="summary" className="space-y-4"><div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle className="text-base">Identificação</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><span className="text-muted-foreground">Marca:</span> {item.brand||'—'}</p><p><span className="text-muted-foreground">Categoria:</span> {item.category||'—'}</p><p><span className="text-muted-foreground">Fonte:</span> {item.ai_source||'manual'} ({Math.round((item.ai_confidence||0)*100)}%)</p></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Valores</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Custo: {money(item.cost)}</p><p>Sugerido: {money(item.suggested_price)}</p><p>Vanguard: {money(item.approved_price)}</p><p>Margem: {margin==null?'—':`${margin.toFixed(1)}%`}</p></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Estoque do CD</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Endereço: {item.warehouse_locations?.code||'Não definido'}</p><p>Catálogo: {item.state==='AVAILABLE'?'Liberado':'Ainda não liberado'}</p></CardContent></Card></div>
        <Card><CardHeader><CardTitle className="text-base">Próxima etapa</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Nome final</Label><Input value={title||item.title||''} onChange={e=>setTitle(e.target.value)}/></div><div className="space-y-2"><Label>SKU</Label><Input value={sku||item.sku||''} onChange={e=>setSku(e.target.value.toUpperCase())}/></div><div className="space-y-2"><Label>Preço Vanguard</Label><Input inputMode="decimal" value={price||item.approved_price||item.suggested_price||''} onChange={e=>setPrice(e.target.value)}/></div><div className="space-y-2"><Label>Endereço</Label><Select value={location||item.location_id||''} onValueChange={setLocation}><SelectTrigger><SelectValue placeholder="Escolha a posição"/></SelectTrigger><SelectContent>{locations.filter(l=>l.is_active).map(l=><SelectItem value={l.id} key={l.id}>{l.code}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Observação</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="flex flex-wrap gap-2">{['IDENTIFIED','QC_PENDING'].includes(item.state)&&allowed(['admin','gestor_cd','qc'])&&<><Button onClick={()=>action.mutate({kind:'qc',decision:'approved'})}><ShieldCheck className="mr-2 h-4 w-4"/>Aprovar QC</Button><Button variant="outline" onClick={()=>action.mutate({kind:'qc',decision:'quarantine'})}>Quarentena</Button><Button variant="destructive" onClick={()=>action.mutate({kind:'qc',decision:'rejected'})}>Reprovar</Button></>}{['QC_APPROVED','PRICED'].includes(item.state)&&allowed(['admin','gestor_cd','commerce'])&&<Button onClick={()=>action.mutate({kind:'price'})}><CheckCircle2 className="mr-2 h-4 w-4"/>Aprovar preço</Button>}{['QC_APPROVED','PRICED','ADDRESS_PENDING'].includes(item.state)&&allowed(['admin','gestor_cd','estoque'])&&<Button variant="outline" onClick={()=>action.mutate({kind:'address'})}><MapPin className="mr-2 h-4 w-4"/>Definir endereço</Button>}{item.state==='ADDRESS_PENDING'&&allowed(['admin','gestor_cd','estoque'])&&<Button onClick={()=>action.mutate({kind:'stock'})}><PackageCheck className="mr-2 h-4 w-4"/>Guardar no CD</Button>}{item.state==='STOCKED'&&allowed(['admin','gestor_cd','commerce'])&&<Button onClick={()=>action.mutate({kind:'release'})}><Send className="mr-2 h-4 w-4"/>Liberar para venda e Bling</Button>}</div></CardContent></Card>
      </TabsContent>
      <TabsContent value="photos" className="space-y-4"><Card><CardContent className="grid gap-3 pt-5 sm:grid-cols-[1fr_auto] sm:items-end"><div className="space-y-2"><Label>Descrição da evidência</Label><Input value={photoCaption} onChange={e=>setPhotoCaption(e.target.value)} placeholder="Ex.: avaria na embalagem"/></div><Button asChild disabled={upload.isPending}><label><Camera className="mr-2 h-4 w-4"/>Adicionar foto<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate(file);e.target.value='';}}/></label></Button></CardContent></Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{photos.length?photos.map(photo=><Card key={photo.id}><CardContent className="pt-5">{photo.signed_url&&<img src={photo.signed_url} alt={photo.caption||'Evidência do produto'} className="mb-3 aspect-square w-full rounded-md border object-cover"/>}<p className="font-medium">{photo.caption||photo.kind}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(photo.created_at).toLocaleString('pt-BR')}</p></CardContent></Card>):<Card><CardContent className="py-12 text-center text-muted-foreground">Nenhuma foto de evidência.</CardContent></Card>}</div></TabsContent>
      <TabsContent value="market"><div className="grid gap-3 md:grid-cols-2">{market.length?market.map(ref=><Card key={ref.id}><CardContent className="pt-5"><p className="font-medium">{ref.title||ref.source}</p><p className="text-sm text-muted-foreground">{ref.source} · {money(ref.price)}</p>{ref.url&&<a className="text-sm text-primary underline" href={ref.url} target="_blank" rel="noreferrer">Abrir referência</a>}</CardContent></Card>):<Card><CardContent className="py-12 text-center text-muted-foreground">Nenhuma referência de preço registrada.</CardContent></Card>}</div></TabsContent>
      <TabsContent value="history"><div className="space-y-2">{[...events,...movements].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(row=><Card key={`${row.id}-${row.action||row.movement_type}`}><CardContent className="py-4"><p className="font-medium">{row.action||row.movement_type}</p><p className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString('pt-BR')} · {row.source||row.warehouse_locations?.code||'CD'}</p></CardContent></Card>)}</div></TabsContent>
    </Tabs></div>;
}